CREATE TABLE IF NOT EXISTS ellsms_direct_send_queue (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    organization_id BIGINT UNSIGNED NULL,
    originator VARCHAR(64) NOT NULL,
    destinations_json JSON NOT NULL,
    content TEXT NOT NULL,
    status ENUM('queued','processing','sent','failed') NOT NULL DEFAULT 'queued',
    attempts INT UNSIGNED NOT NULL DEFAULT 0,
    available_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    claimed_at DATETIME NULL,
    claimed_by VARCHAR(190) NULL,
    completed_at DATETIME NULL,
    result_info VARCHAR(1000) NULL,
    dedup_key CHAR(64) NOT NULL,
    request_id VARCHAR(128) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_direct_send_queue_dedup (dedup_key),
    KEY idx_direct_send_queue_claim (status, available_at, id),
    KEY idx_direct_send_queue_user (user_id, id),
    KEY idx_direct_send_queue_org (organization_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
