<?php
declare(strict_types=1);
/**
 * ELLSMS — durable report export jobs (Phase 8).
 *
 * WHY THIS EXISTS. A CSV export used to run inside the web request: build a WHERE clause, stream
 * rows, write to php://output. That is fine for a few thousand rows and untenable for a few million
 * — the request holds a PHP process and a database cursor open for minutes while the browser times
 * out, and the row count is not knowable before the query runs, so the same URL is harmless for one
 * organization and fatal for another.
 *
 * An export is therefore a JOB. The request records WHAT to export and returns; a dedicated worker
 * (cron/export-worker.php) streams rows to a file in bounded chunks and marks the job ready.
 *
 * ONE FILTER BUILDER, TWO CALLERS. report_export_filter_sql() below is the single place that turns
 * a filter set into SQL. public/reports.php uses it to render the page and the worker uses it to
 * produce the file, so an export can never see rows the report itself would not show. Filters are
 * stored as JSON DATA and re-compiled through this function — a stored filter is never stored SQL,
 * so it cannot become an injection vector no matter what was in the request.
 *
 * TENANT SCOPE IS A FACT OF THE REQUEST. The requester's organization and admin-ness are captured
 * when the job is created and re-applied by the worker from the STORED values. The worker never
 * re-resolves "who can see what" at run time: a user whose role widens between queueing and running
 * must not retroactively widen an export they already requested.
 */

/** Where generated export files live. Deliberately OUTSIDE public/ — see report_export_path(). */
function report_export_dir(): string {
    return dirname(__DIR__, 2) . '/storage/exports';
}

/**
 * Absolute path for a storage key.
 *
 * The key is validated rather than trusted. It is generated by this module as 32 hex characters,
 * so anything else — a slash, a dot, a traversal sequence — means the value did not come from here
 * and is refused. basename() alone would be enough to stop traversal, but rejecting outright makes
 * a tampered key an error instead of a silent read of the wrong file.
 */
function report_export_path(string $storageKey): string {
    if (!preg_match('/^[a-f0-9]{32}\.csv$/', $storageKey)) {
        throw new InvalidArgumentException('Refusing an export storage key that this module did not generate.');
    }
    return report_export_dir() . '/' . $storageKey;
}

/**
 * Compile a stored filter set into a WHERE clause and bound parameters.
 *
 * $filters keys (all optional except the date range):
 *   from, to        Y-m-d date bounds, inclusive of the whole `to` day
 *   status          one of the canonical outbound statuses
 *   dest            destination substring (digits only)
 *   q               message-content substring
 *   user_id         a specific sender (admin-only; ignored otherwise)
 *   member_ids      the organization member ids an ordinary user may see
 *   is_admin        whether the REQUESTER was an admin when the job was created
 *
 * Returns [$whereSql, $params]. Every value is bound, never interpolated.
 */
function report_export_filter_sql(array $filters): array {
    $where  = ['m.sent_at >= ?', 'm.sent_at < DATE_ADD(?, INTERVAL 1 DAY)'];
    $params = [(string)($filters['from'] ?? ''), (string)($filters['to'] ?? '')];

    $isAdmin = !empty($filters['is_admin']);

    if ($isAdmin) {
        // An admin may narrow to one sender, or see everything. There is no org restriction here
        // because that is exactly the platform-admin bypass the report page already grants.
        $userId = (int)($filters['user_id'] ?? 0);
        if ($userId > 0) {
            $where[]  = 'm.sender_user_id = ?';
            $params[] = $userId;
        }
    } else {
        // TENANT ISOLATION. outbound_message is backend-owned and has no organization_id column, so
        // the scope is expressed as "sender_user_id IN (members of my organization)" — the same
        // shape public/reports.php has used since Phase 6.
        //
        // An EMPTY member list must never mean "no restriction". Falling through with no clause
        // would export every organization's messages, so an impossible predicate is emitted
        // instead: a misconfigured job returns nothing rather than everything.
        $memberIds = array_values(array_filter(array_map('intval', (array)($filters['member_ids'] ?? []))));
        if ($memberIds === []) {
            $where[] = '1 = 0';
        } else {
            $where[] = 'm.sender_user_id IN (' . implode(',', array_fill(0, count($memberIds), '?')) . ')';
            array_push($params, ...$memberIds);
        }
    }

    $status = (string)($filters['status'] ?? '');
    if ($status !== '' && in_array($status, ['pending','sent','send_failed','delivered','failed'], true)) {
        $where[]  = 'm.status = ?';
        $params[] = $status;
    }

    $dest = (string)($filters['dest'] ?? '');
    if ($dest !== '') {
        $where[]  = 'm.destination LIKE ?';
        $params[] = '%' . preg_replace('/\D/', '', $dest) . '%';
    }

    $text = (string)($filters['q'] ?? '');
    if ($text !== '') {
        $where[]  = 'm.content LIKE ?';
        $params[] = '%' . $text . '%';
    }

    return [implode(' AND ', $where), $params];
}

/**
 * Queue an export. Returns the new job id.
 *
 * Cheap by design — one INSERT, no counting. Deciding whether the result set is "big" would need
 * the very COUNT(*) this whole mechanism exists to keep off the request path.
 */
function report_export_queue(int $organizationId, int $userId, array $filters, string $downloadFilename): int {
    $ttlHours = max(1, (int)(env('REPORT_EXPORT_TTL_HOURS', '24') ?? '24'));

    $db = db();
    $db->prepare(
        "INSERT INTO ellsms_report_exports
           (organization_id, user_id, filters_json, format, status, download_filename, expires_at)
         VALUES (?, ?, ?, 'csv', 'queued', ?, DATE_ADD(NOW(), INTERVAL ? HOUR))"
    )->execute([
        $organizationId,
        $userId,
        json_encode($filters, JSON_UNESCAPED_UNICODE),
        $downloadFilename,
        $ttlHours,
    ]);

    $id = (int)$db->lastInsertId();
    Logger::info('report_export.queued', [
        'export_id'       => $id,
        'organization_id' => $organizationId,
        'user_id'         => $userId,
        // Filter VALUES are deliberately not logged: a destination or search term is customer data.
        // Which filters were used is enough to debug a slow export.
        'filters_used'    => array_values(array_filter(
            ['status', 'dest', 'q', 'user_id'],
            static fn(string $k): bool => !empty($filters[$k])
        )),
    ]);
    return $id;
}

/**
 * Claim one queued export for this worker.
 *
 * Same compare-and-swap the rest of the project uses (ellsms_import_chunks, ellsms_bulk_items): an
 * UPDATE whose WHERE clause re-states the precondition, so two workers racing on the same row
 * produce one winner and one zero-row update. No SELECT ... FOR UPDATE, no advisory lock.
 *
 * A job whose lease has expired is reclaimable: a worker that was SIGKILLed mid-export leaves its
 * row in 'processing' forever otherwise. Resumption is safe because last_row_id is a keyset cursor
 * — the retry continues from the last row actually written rather than restarting the scan.
 */
function report_export_claim(int $leaseSeconds = 900): ?array {
    $db = db();
    $workerId = worker_id();

    $candidate = $db->query(
        "SELECT id FROM ellsms_report_exports
         WHERE status = 'queued'
            OR (status = 'processing' AND lease_expires_at IS NOT NULL AND lease_expires_at < NOW())
         ORDER BY id
         LIMIT 1"
    )->fetchColumn();

    if ($candidate === false || $candidate === null) {
        return null;
    }

    $claimed = $db->prepare(
        "UPDATE ellsms_report_exports
         SET status = 'processing',
             claimed_by = ?,
             claimed_at = NOW(),
             lease_expires_at = DATE_ADD(NOW(), INTERVAL ? SECOND),
             attempt_count = attempt_count + 1,
             started_at = COALESCE(started_at, NOW())
         WHERE id = ?
           AND (status = 'queued'
                OR (status = 'processing' AND lease_expires_at IS NOT NULL AND lease_expires_at < NOW()))"
    );
    $claimed->execute([$workerId, $leaseSeconds, (int)$candidate]);

    if ($claimed->rowCount() === 0) {
        return null; // another worker won the race
    }

    $st = $db->prepare('SELECT * FROM ellsms_report_exports WHERE id = ?');
    $st->execute([(int)$candidate]);
    $row = $st->fetch();
    return $row ?: null;
}

/** Extend the lease of a long-running export so a slow-but-alive worker is not reclaimed. */
function report_export_touch(int $exportId, int $exportedRows, int $lastRowId, int $leaseSeconds = 900): void {
    db()->prepare(
        "UPDATE ellsms_report_exports
         SET exported_rows = ?, last_row_id = ?, lease_expires_at = DATE_ADD(NOW(), INTERVAL ? SECOND)
         WHERE id = ?"
    )->execute([$exportedRows, $lastRowId, $leaseSeconds, $exportId]);
}

/** Mark an export ready for download. */
function report_export_complete(int $exportId, string $storageKey, int $exportedRows, int $fileBytes): void {
    db()->prepare(
        "UPDATE ellsms_report_exports
         SET status = 'ready', storage_key = ?, exported_rows = ?, file_bytes = ?,
             completed_at = NOW(), lease_expires_at = NULL, error_message = NULL
         WHERE id = ?"
    )->execute([$storageKey, $exportedRows, $fileBytes, $exportId]);

    Logger::info('report_export.ready', [
        'export_id' => $exportId,
        'rows'      => $exportedRows,
        'bytes'     => $fileBytes,
    ]);
}

/**
 * Mark an export failed.
 *
 * The stored message is deliberately generic. An exception message can carry a fragment of SQL or a
 * value from the data, and this string is rendered back to the user on the download page; the full
 * exception goes to the log where only operators can read it.
 */
function report_export_fail(int $exportId, Throwable $t): void {
    db()->prepare(
        "UPDATE ellsms_report_exports
         SET status = 'failed', error_message = ?, completed_at = NOW(), lease_expires_at = NULL
         WHERE id = ?"
    )->execute(['آماده‌سازی خروجی با خطا مواجه شد. لطفاً دوباره تلاش کنید.', $exportId]);

    Logger::error('report_export.failed', ['export_id' => $exportId, 'exception' => $t]);
}

/**
 * List exports visible to one organization, newest first.
 *
 * Bounded by construction — this is a status list, not a report. Scoping is in the SQL, not applied
 * after the fetch, so a tampered id can never widen it.
 */
function report_export_list(int $organizationId, int $limit = 20): array {
    $st = db()->prepare(
        "SELECT id, status, download_filename, total_rows, exported_rows, file_bytes,
                error_message, created_at, completed_at, expires_at
         FROM ellsms_report_exports
         WHERE organization_id = ?
         ORDER BY id DESC
         LIMIT " . max(1, min(100, $limit))
    );
    $st->execute([$organizationId]);
    return $st->fetchAll();
}

/**
 * Fetch one export IF it belongs to the given organization.
 *
 * Scoped in SQL and returns null on mismatch, so an ordinary user changing the id in the URL gets
 * "not found" rather than another tenant's file. Platform admins pass null to bypass, matching the
 * report page's existing admin rule — this does not widen any permission.
 */
function report_export_get(int $exportId, ?int $organizationId): ?array {
    $sql    = 'SELECT * FROM ellsms_report_exports WHERE id = ?';
    $params = [$exportId];
    if ($organizationId !== null) {
        $sql .= ' AND organization_id = ?';
        $params[] = $organizationId;
    }
    $st = db()->prepare($sql);
    $st->execute($params);
    return $st->fetch() ?: null;
}

/**
 * Retention sweep: delete expired files and mark their rows.
 *
 * The FILE is deleted but the ROW is kept, marked 'expired'. The row is the audit trail of who
 * exported what and when — losing that to a cleanup job would remove the record of a bulk data
 * extraction, which is precisely what an auditor needs. Only the payload has a lifetime.
 *
 * Returns the number of exports expired.
 */
function report_export_cleanup(int $limit = 200): int {
    $db = db();
    $due = $db->prepare(
        "SELECT id, storage_key FROM ellsms_report_exports
         WHERE status = 'ready' AND expires_at IS NOT NULL AND expires_at < NOW()
         ORDER BY id
         LIMIT " . max(1, $limit)
    );
    $due->execute();
    $rows = $due->fetchAll();

    $expired = 0;
    foreach ($rows as $row) {
        $key = (string)($row['storage_key'] ?? '');
        if ($key !== '') {
            try {
                $path = report_export_path($key);
                if (is_file($path)) {
                    @unlink($path);
                }
            } catch (InvalidArgumentException) {
                // A key this module could not have generated: leave the file alone and still expire
                // the row, rather than deleting an arbitrary path because a column was tampered with.
            }
        }
        $db->prepare(
            "UPDATE ellsms_report_exports SET status = 'expired', storage_key = NULL WHERE id = ? AND status = 'ready'"
        )->execute([(int)$row['id']]);
        $expired++;
    }

    // Orphaned files: a crash between writing the file and committing 'ready' would otherwise leave
    // customer data on disk forever with no row pointing at it.
    $dir = report_export_dir();
    if (is_dir($dir)) {
        $cutoff = time() - 86400;
        foreach ((glob($dir . '/*.csv') ?: []) as $file) {
            if (@filemtime($file) < $cutoff) {
                $st = $db->prepare('SELECT COUNT(*) FROM ellsms_report_exports WHERE storage_key = ?');
                $st->execute([basename($file)]);
                if ((int)$st->fetchColumn() === 0) {
                    @unlink($file);
                }
            }
        }
    }

    if ($expired > 0) {
        Logger::info('report_export.cleanup', ['expired' => $expired]);
    }
    return $expired;
}
