<?php
require_once __DIR__ . '/../app/bootstrap.php';
$me = require_login();

$userId = (int)($_GET['user'] ?? 0);
$type   = $_GET['type'] ?? '';
if (!$userId || !in_array($type, ['id_card', 'second_doc'], true)) {
    http_response_code(400);
    exit('درخواست نامعتبر است.');
}
if (!is_admin() && $userId !== (int)$me['id']) {
    http_response_code(403);
    exit('اجازه‌ی دسترسی به این فایل را ندارید.');
}

$column = $type === 'id_card' ? 'id_card_photo' : 'second_doc_photo';
$st = db()->prepare("SELECT {$column} AS fn FROM ellsms_user_kyc WHERE user_id = ?");
$st->execute([$userId]);
$filename = $st->fetchColumn();

if (!$filename) {
    http_response_code(404);
    exit('فایلی برای این کاربر ثبت نشده است.');
}

// Defense in depth: filenames are generated by kyc_store_upload() and
// never come from user input at read time, but we still validate the
// shape before touching the filesystem.
if (!preg_match('/^u\d+_[a-z_]+_[0-9a-f]{16}\.(jpg|png|webp|pdf)$/', $filename)) {
    http_response_code(404);
    exit('فایل یافت نشد.');
}
$path = KYC_STORAGE_DIR . '/' . $filename;
if (!is_file($path)) {
    http_response_code(404);
    exit('فایل یافت نشد.');
}

$mimeByExt = ['jpg' => 'image/jpeg', 'png' => 'image/png', 'webp' => 'image/webp', 'pdf' => 'application/pdf'];
$ext = strtolower(pathinfo($filename, PATHINFO_EXTENSION));

header('Content-Type: ' . ($mimeByExt[$ext] ?? 'application/octet-stream'));
header('X-Content-Type-Options: nosniff');
header('Content-Disposition: inline; filename="' . $type . '.' . $ext . '"');
header('Cache-Control: private, max-age=0, no-store');
readfile($path);
