<?php
/**
 * Fast path for large direct/gradual sends generated by public/new-send.php.
 *
 * The legacy import worker is intentionally generic enough for arbitrary CSV/XLSX/P2P imports,
 * but generated direct sends have much stronger invariants: destinations are already normalized
 * and de-duplicated by new-send.php, one CSV record maps to one recipient, and blacklist filtering
 * (when requested) already happened before the temporary CSV was written.
 *
 * Two production bottlenecks made a 100k direct send look like ~500k rows and take minutes:
 *  1) csv_count_rows() counts PHYSICAL lines with fgets(), while fputcsv() correctly embeds a
 *     multi-line SMS body inside one quoted CSV record. A five-line body therefore inflated a
 *     100k-recipient job to roughly 500k "rows".
 *  2) the generic analyze pass re-opens the CSV for every row-range chunk and scans from byte 0,
 *     turning a large CSV into an O(chunks * file_size) workload.
 *
 * This fast path counts CSV RECORDS with fgetcsv(), then streams the file exactly once. It reuses
 * the existing pricing, dedupe, reservation and insert-stage machinery, so accounting semantics do
 * not fork from the normal import pipeline.
 */
declare(strict_types=1);

/** Is this the opaque temporary CSV written by new-send.php (not an arbitrary user upload)? */
function import_fast_generated_simple_job(array $job): bool {
    if (!in_array((string)($job['source_type'] ?? ''), ['p2p', 'gradual'], true)) {
        return false;
    }
    $name = (string)($job['original_filename'] ?? '');
    return preg_match('/^[a-f0-9]{32}\.csv$/', $name) === 1;
}

/** Correct CSV record count; quoted embedded newlines belong to one record, not many rows. */
function import_fast_csv_record_count(string $storageKey): int {
    $path = import_storage_path($storageKey);
    $fh = fopen($path, 'r');
    if (!$fh) {
        throw new RuntimeException('باز کردن فایل واردسازی ممکن نشد.');
    }

    $count = 0;
    while (fgetcsv($fh) !== false) {
        $count++;
    }
    fclose($fh);
    return $count;
}

/** Multi-row INSERT IGNORE into the import dedupe table. Returns rows actually inserted. */
function import_fast_insert_dedupe_batch(PDO $db, int $jobId, array $rows): int {
    if ($rows === []) {
        return 0;
    }

    $placeholders = implode(',', array_fill(0, count($rows), '(?,?,?,?,?)'));
    $flat = [];
    foreach ($rows as $r) {
        $flat[] = $jobId;
        $flat[] = (string)$r['mobile'];
        $flat[] = (string)$r['fingerprint'];
        $flat[] = (string)$r['content'];
        $flat[] = (int)$r['segments'];
    }

    $st = $db->prepare(
        "INSERT IGNORE INTO ellsms_import_dedupe
           (import_job_id, mobile, content_fingerprint, content, segments)
         VALUES {$placeholders}"
    );
    $st->execute($flat);
    return $st->rowCount();
}

/**
 * Analyze a generated direct-send CSV in one forward streaming pass.
 * Progress counters are written after every batch, so /contacts/import remains live.
 */
function import_fast_analyze_generated_job(array $job): void {
    $db = db();
    $jobId = (int)$job['id'];
    $storageKey = (string)$job['storage_key'];
    $batchSize = max(1000, min(20000, (int)(env('FAST_IMPORT_BATCH_SIZE', '10000') ?? '10000')));

    $actualRows = import_fast_csv_record_count($storageKey);
    if ($actualRows <= 0) {
        throw new RuntimeException('فایل واردسازی خالی است.');
    }

    // A generated job is fresh when claimed. Reset stale staging defensively so a prior interrupted
    // pre-confirmation attempt can never multiply recipients on retry.
    db_transaction(function (PDO $db) use ($jobId, $actualRows): void {
        $db->prepare('DELETE FROM ellsms_import_dedupe WHERE import_job_id = ?')->execute([$jobId]);
        $db->prepare("DELETE FROM ellsms_import_chunks WHERE import_job_id = ? AND phase = 'analyze'")->execute([$jobId]);
        $db->prepare(
            "UPDATE ellsms_import_jobs
             SET total_rows=?, processed_rows=0, valid_rows=0, invalid_rows=0,
                 duplicate_rows=0, blacklisted_rows=0, priced_rows=0, unpriced_rows=0,
                 queued_rows=0, estimated_cost_credits=0, error_message=NULL
             WHERE id=?"
        )->execute([$actualRows, $jobId]);
    });

    $totals = [
        'processed' => 0, 'valid' => 0, 'invalid' => 0,
        'duplicate' => 0, 'blacklisted' => 0, 'priced' => 0, 'unpriced' => 0,
    ];

    foreach (import_read_chunks($storageKey, $batchSize) as $rows) {
        $candidates = [];
        foreach ($rows as $row) {
            $totals['processed']++;
            $mobile = (string)($row['mobile'] ?? '');
            $content = trim((string)($row['content'] ?? ''));
            if ($mobile === '' || $content === '') {
                $totals['invalid']++;
                continue;
            }

            // new-send.php already array_unique()s destinations, but retain a local guard so a
            // malformed generated file still cannot duplicate a recipient inside this batch.
            $fingerprint = hash('sha256', $content);
            $key = $mobile . "\0" . $fingerprint;
            if (isset($candidates[$key])) {
                $totals['duplicate']++;
                continue;
            }
            $segments = sms_parts($content);
            $candidates[$key] = [
                'mobile' => $mobile,
                'content' => $content,
                'fingerprint' => $fingerprint,
                'segments' => $segments,
            ];
        }

        $candidateList = array_values($candidates);
        $toPrice = array_map(
            static fn(array $c): array => ['mobile' => $c['mobile'], 'segments' => $c['segments']],
            $candidateList
        );
        $priced = $toPrice === [] ? null : sms_pricing_price_messages(
            $toPrice,
            (string)$job['originator'],
            (string)$job['message_type'],
            (string)$job['analysis_started_at'],
            false
        );

        $insertRows = [];
        foreach ($candidateList as $index => $c) {
            $p = $priced['per_index'][$index] ?? null;
            if ($p === null || !($p['ok'] ?? false)) {
                $totals['unpriced']++;
                continue;
            }
            $insertRows[] = $c;
        }

        // Keep each SQL statement well below MySQL's prepared-parameter ceiling.
        $inserted = 0;
        foreach (array_chunk($insertRows, 2000) as $sqlBatch) {
            $inserted += import_fast_insert_dedupe_batch($db, $jobId, $sqlBatch);
        }
        $ignored = count($insertRows) - $inserted;
        if ($ignored > 0) {
            $totals['duplicate'] += $ignored;
        }
        $totals['valid'] += $inserted;
        $totals['priced'] += $inserted;

        $db->prepare(
            "UPDATE ellsms_import_jobs
             SET processed_rows=?, valid_rows=?, invalid_rows=?, duplicate_rows=?,
                 blacklisted_rows=?, priced_rows=?, unpriced_rows=?
             WHERE id=? AND status='analyzing'"
        )->execute([
            $totals['processed'], $totals['valid'], $totals['invalid'], $totals['duplicate'],
            $totals['blacklisted'], $totals['priced'], $totals['unpriced'], $jobId,
        ]);

        // Cancellation must take effect between batches, not after the whole 100k/500k file.
        $statusSt = $db->prepare('SELECT status FROM ellsms_import_jobs WHERE id=?');
        $statusSt->execute([$jobId]);
        if ((string)$statusSt->fetchColumn() === 'cancelled') {
            Logger::info('import.fast.cancelled', ['import_job_id' => $jobId, 'processed' => $totals['processed']]);
            return;
        }
    }

    // One completed analyze chunk is enough for the existing reserve/stage code, which only needs
    // aggregate counters from completed analyze chunks.
    $db->prepare(
        "INSERT INTO ellsms_import_chunks
           (import_job_id, chunk_no, phase, first_row, last_row, status,
            rows_total, rows_valid, rows_invalid, rows_duplicate, rows_blacklisted, rows_priced, rows_unpriced)
         VALUES (?,?,?,?,?,'completed',?,?,?,?,?,?,?)"
    )->execute([
        $jobId, 1, 'analyze', 1, max(1, $totals['processed']),
        $totals['processed'], $totals['valid'], $totals['invalid'], $totals['duplicate'],
        $totals['blacklisted'], $totals['priced'], $totals['unpriced'],
    ]);

    // Re-load so the generic reservation/staging code sees the corrected total and counters.
    $fresh = import_load_job($jobId, null);
    if ($fresh === null || (string)$fresh['status'] !== 'analyzing') {
        return;
    }
    import_job_reserve_and_stage($fresh);

    Logger::info('import.fast.analysis.completed', [
        'import_job_id' => $jobId,
        'actual_rows' => $actualRows,
        'processed' => $totals['processed'],
        'priced' => $totals['priced'],
        'invalid' => $totals['invalid'],
        'duplicate' => $totals['duplicate'],
    ]);
}

/**
 * Replacement loop body used by cron/import-worker.php.
 * Existing insert chunks remain first-class and are processed before starting a new file.
 */
function import_fast_worker_run_once(): int {
    $insertChunk = import_claim_insert_chunk();
    if ($insertChunk !== null) {
        import_process_insert_chunk($insertChunk);
        return 1;
    }

    $job = import_claim_uploaded_job();
    if ($job === null) {
        return 0;
    }

    if (!import_fast_generated_simple_job($job)) {
        import_job_run_analysis((int)$job['id']);
        return 1;
    }

    try {
        import_fast_analyze_generated_job($job);
    } catch (Throwable $t) {
        Logger::error('import.fast.analysis.failed', ['import_job_id' => (int)$job['id'], 'exception' => $t]);
        db()->prepare("UPDATE ellsms_import_jobs SET status='failed', error_message=?, completed_at=NOW() WHERE id=?")
            ->execute([mb_strimwidth($t->getMessage(), 0, 500, '…'), (int)$job['id']]);
        wallet_release_reservation('import_job', (string)$job['id']);
        usage_release_messages('import_job', (string)$job['id']);
    }
    return 1;
}
