<?php
/**
 * ELLSMS — shared price-quote/invoice document model.
 *
 * One JSON document (ellsms_settings.price_quote_document) backs both the
 * admin's editable web page (public/price-quote.php) and the Telegram bot
 * command that regenerates the same document as a PDF on request
 * (public/telegram-webhook.php). Keeping the schema/defaults/HTML render in
 * one place means a field added in one surface can't drift from the other.
 */

const PRICE_QUOTE_SETTING_KEY = 'price_quote_document';

function price_quote_default(): array {
    [$jy] = gregorian_to_jalali((int)date('Y'), (int)date('n'), (int)date('j'));
    return [
        'invoice_no'     => 'ELL-' . $jy . '-001',
        'date'           => jdate(date('Y-m-d H:i:s'), false),
        'validity_days'  => '7',
        'price_unit'     => 'تومان',
        'title'          => 'فاکتور / لیست قیمت خدمات پیامک',
        'subtitle'       => 'ELLSMS Smart SMS Panel',
        'rows' => [
            ['title' => 'پیامک حقوقی',              'desc' => 'مناسب فاکتور رسمی / شرکتی',            'unit' => 'هر پیامک', 'price' => '115'],
            ['title' => 'پیامک غیررسمی',             'desc' => 'مناسب فاکتور شخصی / غیررسمی',          'unit' => 'هر پیامک', 'price' => '110'],
            ['title' => 'پیامک بالک منطقه‌ای',        'desc' => 'ارسال هدفمند بر اساس مناطق دارای دیتا (برای مناطقی که دیتا نداریم)', 'unit' => 'هر پیامک', 'price' => '145'],
            ['title' => 'LBA',                        'desc' => 'ارسال مبتنی بر موقعیت مکانی',          'unit' => 'هر پیامک', 'price' => '400'],
        ],
        'notes' => [
            'تمام قیمت‌ها به ازای هر پیامک محاسبه می‌شوند.',
            'تعرفه‌ها ممکن است بر اساس حجم ارسال با شرایط همکاری تغییر کنند.',
            'برای دریافت مشاوره و خرید پنل، با واحد فروش ELLSMS تماس بگیرید.',
        ],
        'features' => ['پایداری و امنیت', 'پشتیبانی حرفه‌ای', 'ارسال سریع', 'پوشش سراسری'],
        'phone1'   => '۰۹۱۲۳۳۴۸۴۱۷',
        'phone2'   => '۰۹۱۹۷۶۸۴۰۶۳',
        'website'  => 'www.ellsms.ir',
        'email'    => 'sales@ellsms.ir',
        'footer_tagline' => 'با ELLSMS بیشتر دیده شوید ...',
    ];
}

function price_quote_load(): array {
    $raw = setting(PRICE_QUOTE_SETTING_KEY);
    if (!$raw) return price_quote_default();
    $data = json_decode($raw, true);
    if (!is_array($data)) return price_quote_default();
    return array_replace(price_quote_default(), $data);
}

function price_quote_save(array $data): void {
    set_setting(PRICE_QUOTE_SETTING_KEY, json_encode($data, JSON_UNESCAPED_UNICODE));
}

/**
 * Renders the document as a standalone HTML string (no editable form
 * controls) suitable for wkhtmltopdf. Kept visually close to
 * public/price-quote.php so a PDF generated by the bot looks like what the
 * admin sees on screen. Fonts are referenced as local file:// paths (TTF,
 * not the browser's woff2 copies) since wkhtmltopdf's rendering engine
 * needs --enable-local-file-access to read them — see price_quote_render_pdf().
 *
 * wkhtmltopdf's bundled WebKit (an old, patched Qt WebKit — see the
 * Dockerfile comment on why it is used at all) does not reliably reproduce
 * the CSS this project's browser pages use for the gradient/decorative
 * header band (a plain `background-color` fallback kept it from going fully
 * blank, but still looked flat and off-brand next to the real design). The
 * band's artwork — gradient, decorative shapes, the ELLSMS wordmark, the
 * "پیامک قدرت ارتباط است" ribbon — is therefore a single pre-rendered PNG
 * (public/assets/img/price-quote-band.png, rendered once with a real
 * browser engine; regenerate it the same way if the design changes: open
 * the small standalone HTML this docblock's sibling data lives next to, or
 * ask for it to be redone). An image is something ANY renderer, however
 * old, can just place — no gradient/flexbox/shape support required. Only
 * the genuinely dynamic part (invoice title/subtitle) is real HTML text,
 * overlaid on top of that image via `.band`'s background-image.
 */
function price_quote_render_html(array $doc): string {
    $fontPath = 'file://' . APP_ROOT . '/public/assets/fonts';
    $bandImagePath = 'file://' . APP_ROOT . '/public/assets/img/price-quote-band.png';
    $rowsHtml = '';
    foreach ($doc['rows'] as $i => $row) {
        $rowsHtml .= '<tr>'
            . '<td class="num">' . e(to_persian_digits((string)($i + 1))) . '</td>'
            . '<td><div class="row-title">' . e($row['title']) . '</div>'
            . ($row['desc'] !== '' ? '<div class="row-desc">' . e($row['desc']) . '</div>' : '')
            . '</td>'
            . '<td class="center">' . e($row['unit']) . '</td>'
            . '<td class="center">' . e(to_persian_digits((string)$row['price'])) . '</td>'
            . '</tr>';
    }
    $notesHtml = '';
    foreach ($doc['notes'] as $note) {
        $notesHtml .= '<div class="note-line">' . e($note) . '</div>';
    }
    $featuresHtml = '';
    foreach ($doc['features'] as $f) {
        $featuresHtml .= '<div class="feature">' . e($f) . '</div>';
    }

    return '<!doctype html><html dir="rtl" lang="fa"><head><meta charset="utf-8"><style>
        @font-face { font-family: Vazirmatn; src: url("' . $fontPath . '/Vazirmatn-Regular.ttf"); font-weight: 400; }
        @font-face { font-family: Vazirmatn; src: url("' . $fontPath . '/Vazirmatn-Bold.ttf"); font-weight: 700; }
        * { box-sizing: border-box; }
        body { font-family: Vazirmatn, sans-serif; color:#1a2036; margin:0; }
        /* background-color is the fallback if the image itself fails to load for some reason;
           background-size:100% 100% stretches the (fixed 1000x170) artwork to fill whatever
           width wkhtmltopdf actually lays out, keeping the ribbon/wordmark fully visible instead
           of risking a `cover` crop at unknown container widths. */
        .band { background-color: #4b3fd6; background-image: url("' . $bandImagePath . '"); background-size: 100% 100%; background-repeat: no-repeat; color:#fff; padding: 74px 26px 14px; height: 128px; }
        .title { font-size:20px; font-weight:700; }
        .subtitle { font-size:11px; opacity:.9; margin-top:2px; }
        .meta { display:flex; gap:16px; flex-wrap:wrap; padding:12px 26px; background:#f6f8ff; border-bottom:1px solid #e5e8f5; font-size:11px; color:#4a5170; }
        .meta b { color:#8890ad; font-weight:400; }
        .body { padding: 16px 26px; }
        table { width:100%; border-collapse:collapse; border:1px solid #e5e8f5; }
        thead th { background:#5b3df0; color:#fff; font-size:11px; padding:8px 10px; text-align:right; }
        thead th.num-col { width:36px; text-align:center; }
        thead th.unit-col, thead th.price-col { width:90px; text-align:center; }
        tbody td { border-top:1px solid #eef0fa; padding:7px 10px; font-size:11px; }
        tbody tr:nth-child(even) { background:#fafbff; }
        .num, .center { text-align:center; }
        .row-title { font-weight:700; }
        .row-desc { color:#6b7290; font-size:10px; margin-top:2px; }
        .notes { margin-top:14px; background:#f6f8ff; border:1px solid #e5e8f5; border-radius:6px; padding:10px 14px; }
        .notes h4 { margin:0 0 6px; font-size:12px; color:#3a3f66; }
        .note-line { font-size:10.5px; color:#454a6b; margin-bottom:4px; }
        .note-line:before { content:"● "; }
        .features { margin-top:14px; }
        .features .feature { display:inline-block; width:23%; background:#f6f8ff; border:1px solid #e5e8f5; border-radius:6px; padding:8px; text-align:center; font-size:10px; color:#3a3f66; margin-inline-end:1%; }
        .foot { margin-top:16px; padding:12px 26px; background:#151a24; color:#d8deea; font-size:10.5px; display:flex; justify-content:space-between; flex-wrap:wrap; gap:8px; }
    </style></head><body>
        <div class="band">
            <div class="title">' . e($doc['title']) . '</div>
            <div class="subtitle">' . e($doc['subtitle']) . '</div>
        </div>
        <div class="meta">
            <div><b>شماره فاکتور:</b> ' . e($doc['invoice_no']) . '</div>
            <div><b>تاریخ:</b> ' . e($doc['date']) . '</div>
            <div><b>اعتبار قیمت:</b> ' . e(to_persian_digits((string)$doc['validity_days'])) . ' روز</div>
            <div><b>واحد قیمت:</b> ' . e($doc['price_unit']) . '</div>
        </div>
        <div class="body">
            <table>
                <thead><tr>
                    <th class="num-col">ردیف</th><th>شرح خدمت</th><th class="unit-col">واحد</th><th class="price-col">قیمت</th>
                </tr></thead>
                <tbody>' . $rowsHtml . '</tbody>
            </table>
            <div class="notes"><h4>نکات مهم</h4>' . $notesHtml . '</div>
            <div class="features">' . $featuresHtml . '</div>
        </div>
        <div class="foot">
            <div>ELLSMS</div>
            <div>' . e($doc['phone1']) . ' — ' . e($doc['phone2']) . ' — ' . e($doc['website']) . ' — ' . e($doc['email']) . '</div>
        </div>
    </body></html>';
}

/**
 * Renders HTML to a PDF via the local wkhtmltopdf binary (installed in the
 * Docker image — see docker/Dockerfile). No PHP PDF library is used: this
 * project ships zero production Composer dependencies by design (only
 * PHPUnit is a require-dev), so shelling out to one local, version-pinned
 * binary with a fully-controlled argv (proc_open + bypass_shell, the same
 * pattern app/TotpMfa.php uses for qrencode) is the fit here, not adding a
 * package tree that never gets installed in production anyway.
 *
 * Returns the raw PDF bytes, or null if the binary is missing or the render
 * fails — callers must treat null as "PDF export unavailable on this
 * server" and say so, never as an empty-but-valid file.
 */
function price_quote_render_pdf(string $html): ?string {
    if (!function_exists('proc_open')) return null;

    $descriptors = [
        0 => ['pipe', 'r'],
        1 => ['pipe', 'w'],
        2 => ['pipe', 'w'],
    ];
    $pipes = [];
    $process = @proc_open(
        ['wkhtmltopdf', '--quiet', '--enable-local-file-access', '--page-size', 'A4', '--encoding', 'utf-8', '-', '-'],
        $descriptors,
        $pipes,
        null,
        null,
        ['bypass_shell' => true]
    );
    if (!is_resource($process)) return null;

    fwrite($pipes[0], $html);
    fclose($pipes[0]);
    $pdf = stream_get_contents($pipes[1]);
    $stderr = stream_get_contents($pipes[2]);
    fclose($pipes[1]);
    fclose($pipes[2]);
    $exit = proc_close($process);

    if ($exit !== 0 || !is_string($pdf) || substr($pdf, 0, 4) !== '%PDF') {
        Logger::warning('price_quote.pdf_render_failed', ['exit' => $exit, 'stderr_present' => trim((string)$stderr) !== '']);
        return null;
    }
    return $pdf;
}

/**
 * Parses a Telegram /invoice command into an override of $baseDoc (normally
 * price_quote_load() — the admin's saved template). Only what the sender
 * actually wrote changes; everything else (branding, contact footer, and
 * rows/notes if none were given) stays as configured in the admin panel.
 * Recognized lines (any order, Persian labels, "label: value"):
 *   شماره / تاریخ / اعتبار / واحد / عنوان / زیرعنوان / پاورقی / تلفن۱ / تلفن۲ / وبسایت / ایمیل
 *   ردیف: عنوان | توضیح | واحد | قیمت   (repeatable — replaces all rows)
 *   نکته: متن                           (repeatable — replaces all notes)
 */
function price_quote_parse_telegram_message(string $text, array $baseDoc): array {
    $fieldMap = [
        'شماره'      => 'invoice_no',
        'شماره فاکتور' => 'invoice_no',
        'تاریخ'      => 'date',
        'اعتبار'     => 'validity_days',
        'واحد'       => 'price_unit',
        'عنوان'      => 'title',
        'زیرعنوان'   => 'subtitle',
        'پاورقی'     => 'footer_tagline',
        'تلفن1'      => 'phone1',
        'تلفن۱'      => 'phone1',
        'تلفن'       => 'phone1',
        'تلفن2'      => 'phone2',
        'تلفن۲'      => 'phone2',
        'وبسایت'     => 'website',
        'سایت'       => 'website',
        'ایمیل'      => 'email',
    ];

    $doc = $baseDoc;
    $rows = [];
    $notes = [];
    $sawRows = false;
    $sawNotes = false;

    foreach (preg_split('/\r\n|\r|\n/', $text) as $line) {
        $line = trim($line);
        if ($line === '' || str_starts_with($line, '/invoice')) continue;
        $colon = mb_strpos($line, ':');
        if ($colon === false) $colon = mb_strpos($line, '：'); // fullwidth colon, common on mobile keyboards
        if ($colon === false) continue;

        $label = from_persian_digits(trim(mb_substr($line, 0, $colon)));
        $value = trim(mb_substr($line, $colon + 1));

        if ($label === 'ردیف') {
            $parts = array_map('trim', explode('|', $value));
            $title = $parts[0] ?? '';
            if ($title === '') continue;
            $rows[] = [
                'title' => $title,
                'desc'  => $parts[1] ?? '',
                'unit'  => $parts[2] ?? 'هر پیامک',
                'price' => from_persian_digits($parts[3] ?? ''),
            ];
            $sawRows = true;
            continue;
        }
        if ($label === 'نکته') {
            if ($value !== '') $notes[] = $value;
            $sawNotes = true;
            continue;
        }
        if (isset($fieldMap[$label])) {
            $doc[$fieldMap[$label]] = $label === 'اعتبار' ? from_persian_digits($value) : $value;
        }
    }

    if ($sawRows) $doc['rows'] = $rows;
    if ($sawNotes) $doc['notes'] = $notes;
    return $doc;
}
