<?php
/**
 * ELLSMS — prints the actual, currently-enforced owner/admin/member permission matrix (Phase 7,
 * STEP 40). Reads directly from app/rbac.php's role_permissions() and
 * app/Support/Permissions.php's catalog — never a hand-maintained copy that could drift from what
 * the code actually enforces (docs/rbac-architecture.md's own matrix is generated by hand from this
 * same source and should be regenerated from here if the two ever disagree).
 *
 * Read-only. No database connection is even needed (permissions are compile-time constants, Option
 * A design) — loads only enough of the app to get Permissions/role_permissions() defined.
 *
 * Usage: php cron/rbac-status.php
 */
require_once __DIR__ . '/../app/Support/Permissions.php';
require_once __DIR__ . '/../app/Support/Logger.php';

// role_permissions() itself lives in app/rbac.php; that file also defines
// organization_change_member_role()/organization_remove_member() (which call db_transaction() from
// app/bootstrap.php) but neither is invoked here — PHP only needs the FUNCTIONS DEFINED, not called,
// so app/rbac.php loads standalone without needing the rest of app/bootstrap.php's DB-touching
// require chain. This keeps rbac-status.php genuinely read-only with no database connection at all.
require_once __DIR__ . '/../app/rbac.php';

$roles = ['owner', 'admin', 'member'];
$permissions = Permissions::all();

$colWidth = max(array_map('strlen', $permissions)) + 2;
printf("%-{$colWidth}s %-6s %-6s %-6s\n", 'permission', 'owner', 'admin', 'member');
echo str_repeat('-', $colWidth + 20) . "\n";
foreach ($permissions as $permission) {
    $row = [$permission];
    foreach ($roles as $role) {
        $row[] = in_array($permission, role_permissions($role), true) ? 'yes' : '-';
    }
    printf("%-{$colWidth}s %-6s %-6s %-6s\n", ...$row);
}

echo "\nReserved permissions (catalog-complete, not yet wired to any organization-scoped feature —\n";
echo "see app/Support/Permissions.php's own per-constant docblocks for exactly why): \n";
foreach ([Permissions::SENDER_MANAGE, Permissions::WALLET_ADJUST, Permissions::KYC_VIEW, Permissions::KYC_MANAGE, Permissions::AUDIT_VIEW] as $reserved) {
    echo "  - {$reserved}\n";
}
